buildscript {
	repositories {
		maven { url "https://repo.grails.org/grails/core/" }
	}
	dependencies {
		classpath platform("org.grails:grails-bom:${grailsVersion}")
		classpath "org.grails:grails-gradle-plugin"
		classpath "com.adarshr.test-logger:com.adarshr.test-logger.gradle.plugin:4.0.0"
	}
}

allprojects {
	repositories {
		maven { url "https://repo.grails.org/grails/core" }
	}
}

version project.projectVersion
group "org.grails.plugins"

subprojects {
	version project.projectVersion
	group "org.grails.plugins"

	if (project.name == 'grails-db-reverse-engineer') {
		apply plugin: "org.grails.grails-publish"
		grailsPublish {
			githubSlug = 'grails-plugins/grails-db-reverse-engineer'
			license {
				name = 'Apache-2.0'
			}
			title = 'DB Reverse Engineering Plugin'
			desc = 'Given a database, this plugin generates Grails domain classes from it.'
			developers = [burtbeckwith: "Burt Beckwith"]
		}
	}
}

apply from: rootProject.file("gradle/docs.gradle")
